# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2172b73ea3ba2d6f481d740e016ad1c8e67e418623bdd0b0688c5840153a475f5c8ff646302486baedf023c7704605f0b06f8cd11ec8e4026b495573f46ce1

test:
  secret_key_base: 8d914488b77e2b1dd3576d299840d35d1d7d104d06f0a0f9560fd4d22c4b39a927ae28229ad373ca8e4ca001918a8b6dbe5841ed2113ac50738445ddfdbcabe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
